spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courses?useUnicode=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 158Asapum
  jpa:
    hibernate:
      ddl-auto: none

someParameter:
  value: 5463